export enum NotificationType {
  NEW_LISTING = 'NEW_LISTING',
  PRICE_DROP = 'PRICE_DROP',
  NEW_MESSAGE = 'NEW_MESSAGE',
  LISTING_VERIFIED = 'LISTING_VERIFIED',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  ESCROW_RELEASED = 'ESCROW_RELEASED',
  REVIEW_RECEIVED = 'REVIEW_RECEIVED',
  ACCOUNT_VERIFIED = 'ACCOUNT_VERIFIED',
  WELCOME = 'WELCOME',
  SYSTEM_ANNOUNCEMENT = 'SYSTEM_ANNOUNCEMENT',
}
