export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  MODERATOR = 'MODERATOR',
  VERIFIED_DALAAL = 'VERIFIED_DALAAL',
  REGULAR_DALAAL = 'REGULAR_DALAAL',
  PROPERTY_OWNER = 'PROPERTY_OWNER',
  VEHICLE_OWNER = 'VEHICLE_OWNER',
  CUSTOMER = 'CUSTOMER',
}
