import { EscrowRepository } from './escrow.repository';
import { CreateEscrowDto } from './dto';
export declare class EscrowService {
    private readonly escrowRepository;
    constructor(escrowRepository: EscrowRepository);
    createEscrow(buyerId: string, dto: CreateEscrowDto): Promise<{
        id: string;
        status: import(".prisma/client").$Enums.EscrowStatus;
        createdAt: Date;
        updatedAt: Date;
        paymentId: string | null;
        amount: import("@prisma/client/runtime/library").Decimal;
        currency: string;
        platformFee: import("@prisma/client/runtime/library").Decimal;
        netAmount: import("@prisma/client/runtime/library").Decimal;
        buyerConfirmed: boolean;
        sellerConfirmed: boolean;
        releasedAt: Date | null;
        isDisputed: boolean;
        disputedAt: Date | null;
        disputeReason: string | null;
        sellerId: string;
        listingId: string;
        buyerId: string;
    }>;
    getMyEscrows(userId: string): Promise<({
        listing: {
            description: string | null;
            id: string;
            status: import(".prisma/client").$Enums.ListingStatus;
            createdAt: Date;
            updatedAt: Date;
            userId: string;
            currency: string;
            type: import(".prisma/client").$Enums.ListingType;
            title: string;
            slug: string;
            price: import("@prisma/client/runtime/library").Decimal;
            priceNegotiable: boolean;
            city: string;
            district: string | null;
            address: string | null;
            latitude: number | null;
            longitude: number | null;
            isVerified: boolean;
            isFeatured: boolean;
            viewCount: number;
            favoriteCount: number;
            inquiryCount: number;
            featuredImage: string | null;
            videoUrl: string | null;
            availableFrom: Date | null;
            expiresAt: Date | null;
            publishedAt: Date | null;
        };
        seller: {
            email: string;
            password: string | null;
            id: string;
            phone: string | null;
            googleId: string | null;
            role: import(".prisma/client").$Enums.UserRole;
            status: import(".prisma/client").$Enums.UserStatus;
            emailVerified: boolean;
            phoneVerified: boolean;
            twoFactorEnabled: boolean;
            lastLoginAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
        };
        buyer: {
            email: string;
            password: string | null;
            id: string;
            phone: string | null;
            googleId: string | null;
            role: import(".prisma/client").$Enums.UserRole;
            status: import(".prisma/client").$Enums.UserStatus;
            emailVerified: boolean;
            phoneVerified: boolean;
            twoFactorEnabled: boolean;
            lastLoginAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
        };
    } & {
        id: string;
        status: import(".prisma/client").$Enums.EscrowStatus;
        createdAt: Date;
        updatedAt: Date;
        paymentId: string | null;
        amount: import("@prisma/client/runtime/library").Decimal;
        currency: string;
        platformFee: import("@prisma/client/runtime/library").Decimal;
        netAmount: import("@prisma/client/runtime/library").Decimal;
        buyerConfirmed: boolean;
        sellerConfirmed: boolean;
        releasedAt: Date | null;
        isDisputed: boolean;
        disputedAt: Date | null;
        disputeReason: string | null;
        sellerId: string;
        listingId: string;
        buyerId: string;
    })[]>;
    releaseEscrow(escrowId: string, userId: string): Promise<{
        id: string;
        status: import(".prisma/client").$Enums.EscrowStatus;
        createdAt: Date;
        updatedAt: Date;
        paymentId: string | null;
        amount: import("@prisma/client/runtime/library").Decimal;
        currency: string;
        platformFee: import("@prisma/client/runtime/library").Decimal;
        netAmount: import("@prisma/client/runtime/library").Decimal;
        buyerConfirmed: boolean;
        sellerConfirmed: boolean;
        releasedAt: Date | null;
        isDisputed: boolean;
        disputedAt: Date | null;
        disputeReason: string | null;
        sellerId: string;
        listingId: string;
        buyerId: string;
    }>;
}
