import { PrismaService } from '../database/prisma.service';
export declare class ModerationService {
    private readonly prisma;
    constructor(prisma: PrismaService);
    getPendingListings(): Promise<({
        user: {
            profile: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                userId: string;
                currency: string | null;
                city: string | null;
                firstName: string | null;
                lastName: string | null;
                avatar: string | null;
                bio: string | null;
                country: string | null;
                isDiaspora: boolean;
                language: string | null;
                whatsappNumber: string | null;
                telegramHandle: string | null;
                totalListings: number;
                rating: number | null;
                reviewCount: number;
                responseRate: number | null;
            } | null;
        } & {
            email: string;
            password: string | null;
            id: string;
            phone: string | null;
            googleId: string | null;
            role: import(".prisma/client").$Enums.UserRole;
            status: import(".prisma/client").$Enums.UserStatus;
            emailVerified: boolean;
            phoneVerified: boolean;
            twoFactorEnabled: boolean;
            lastLoginAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
        };
    } & {
        description: string | null;
        id: string;
        status: import(".prisma/client").$Enums.ListingStatus;
        createdAt: Date;
        updatedAt: Date;
        userId: string;
        currency: string;
        type: import(".prisma/client").$Enums.ListingType;
        title: string;
        slug: string;
        price: import("@prisma/client/runtime/library").Decimal;
        priceNegotiable: boolean;
        city: string;
        district: string | null;
        address: string | null;
        latitude: number | null;
        longitude: number | null;
        isVerified: boolean;
        isFeatured: boolean;
        viewCount: number;
        favoriteCount: number;
        inquiryCount: number;
        featuredImage: string | null;
        videoUrl: string | null;
        availableFrom: Date | null;
        expiresAt: Date | null;
        publishedAt: Date | null;
    })[]>;
    approveListing(id: string): Promise<{
        description: string | null;
        id: string;
        status: import(".prisma/client").$Enums.ListingStatus;
        createdAt: Date;
        updatedAt: Date;
        userId: string;
        currency: string;
        type: import(".prisma/client").$Enums.ListingType;
        title: string;
        slug: string;
        price: import("@prisma/client/runtime/library").Decimal;
        priceNegotiable: boolean;
        city: string;
        district: string | null;
        address: string | null;
        latitude: number | null;
        longitude: number | null;
        isVerified: boolean;
        isFeatured: boolean;
        viewCount: number;
        favoriteCount: number;
        inquiryCount: number;
        featuredImage: string | null;
        videoUrl: string | null;
        availableFrom: Date | null;
        expiresAt: Date | null;
        publishedAt: Date | null;
    }>;
    rejectListing(id: string, reason: string): Promise<{
        description: string | null;
        id: string;
        status: import(".prisma/client").$Enums.ListingStatus;
        createdAt: Date;
        updatedAt: Date;
        userId: string;
        currency: string;
        type: import(".prisma/client").$Enums.ListingType;
        title: string;
        slug: string;
        price: import("@prisma/client/runtime/library").Decimal;
        priceNegotiable: boolean;
        city: string;
        district: string | null;
        address: string | null;
        latitude: number | null;
        longitude: number | null;
        isVerified: boolean;
        isFeatured: boolean;
        viewCount: number;
        favoriteCount: number;
        inquiryCount: number;
        featuredImage: string | null;
        videoUrl: string | null;
        availableFrom: Date | null;
        expiresAt: Date | null;
        publishedAt: Date | null;
    }>;
}
