# ============================================
# Backend Dockerfile (Development)
# ============================================

FROM node:20

WORKDIR /app

COPY package*.json ./
RUN npm install --legacy-peer-deps

RUN npm install -g prisma

COPY . .

RUN npx prisma generate

EXPOSE 3002

COPY docker-entrypoint.dev.sh /docker-entrypoint.dev.sh
RUN chmod +x /docker-entrypoint.dev.sh

CMD ["/docker-entrypoint.dev.sh"]
