export declare enum PaymentType {
    LISTING_FEE = "LISTING_FEE",
    PREMIUM_FEATURE = "PREMIUM_FEATURE",
    ESCROW_DEPOSIT = "ESCROW_DEPOSIT",
    ESCROW_RELEASE = "ESCROW_RELEASE",
    COMMISSION = "COMMISSION"
}
