import { PrismaService } from '../database/prisma.service';
import { Prisma } from '@prisma/client';
export declare class UsersRepository {
    private readonly prisma;
    constructor(prisma: PrismaService);
    findAll(args?: Prisma.UserFindManyArgs): Promise<({
        profile: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            userId: string;
            currency: string | null;
            city: string | null;
            firstName: string | null;
            lastName: string | null;
            avatar: string | null;
            bio: string | null;
            country: string | null;
            isDiaspora: boolean;
            language: string | null;
            whatsappNumber: string | null;
            telegramHandle: string | null;
            totalListings: number;
            rating: number | null;
            reviewCount: number;
            responseRate: number | null;
        } | null;
    } & {
        email: string;
        password: string | null;
        id: string;
        phone: string | null;
        googleId: string | null;
        role: import(".prisma/client").$Enums.UserRole;
        status: import(".prisma/client").$Enums.UserStatus;
        emailVerified: boolean;
        phoneVerified: boolean;
        twoFactorEnabled: boolean;
        lastLoginAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
    })[]>;
    findById(id: string): Promise<{
        profile: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            userId: string;
            currency: string | null;
            city: string | null;
            firstName: string | null;
            lastName: string | null;
            avatar: string | null;
            bio: string | null;
            country: string | null;
            isDiaspora: boolean;
            language: string | null;
            whatsappNumber: string | null;
            telegramHandle: string | null;
            totalListings: number;
            rating: number | null;
            reviewCount: number;
            responseRate: number | null;
        } | null;
        verification: {
            id: string;
            status: import(".prisma/client").$Enums.VerificationStatus;
            createdAt: Date;
            updatedAt: Date;
            userId: string;
            documentType: import(".prisma/client").$Enums.DocumentType;
            documentNumber: string | null;
            documentImage: string | null;
            selfieImage: string | null;
            businessLicense: string | null;
            submittedAt: Date;
            reviewedAt: Date | null;
            rejectionReason: string | null;
        } | null;
    } & {
        email: string;
        password: string | null;
        id: string;
        phone: string | null;
        googleId: string | null;
        role: import(".prisma/client").$Enums.UserRole;
        status: import(".prisma/client").$Enums.UserStatus;
        emailVerified: boolean;
        phoneVerified: boolean;
        twoFactorEnabled: boolean;
        lastLoginAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    findByEmail(email: string): Promise<({
        profile: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            userId: string;
            currency: string | null;
            city: string | null;
            firstName: string | null;
            lastName: string | null;
            avatar: string | null;
            bio: string | null;
            country: string | null;
            isDiaspora: boolean;
            language: string | null;
            whatsappNumber: string | null;
            telegramHandle: string | null;
            totalListings: number;
            rating: number | null;
            reviewCount: number;
            responseRate: number | null;
        } | null;
    } & {
        email: string;
        password: string | null;
        id: string;
        phone: string | null;
        googleId: string | null;
        role: import(".prisma/client").$Enums.UserRole;
        status: import(".prisma/client").$Enums.UserStatus;
        emailVerified: boolean;
        phoneVerified: boolean;
        twoFactorEnabled: boolean;
        lastLoginAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
    }) | null>;
    create(data: Prisma.UserCreateInput): Promise<{
        email: string;
        password: string | null;
        id: string;
        phone: string | null;
        googleId: string | null;
        role: import(".prisma/client").$Enums.UserRole;
        status: import(".prisma/client").$Enums.UserStatus;
        emailVerified: boolean;
        phoneVerified: boolean;
        twoFactorEnabled: boolean;
        lastLoginAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    update(id: string, data: Prisma.UserUpdateInput): Promise<{
        profile: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            userId: string;
            currency: string | null;
            city: string | null;
            firstName: string | null;
            lastName: string | null;
            avatar: string | null;
            bio: string | null;
            country: string | null;
            isDiaspora: boolean;
            language: string | null;
            whatsappNumber: string | null;
            telegramHandle: string | null;
            totalListings: number;
            rating: number | null;
            reviewCount: number;
            responseRate: number | null;
        } | null;
    } & {
        email: string;
        password: string | null;
        id: string;
        phone: string | null;
        googleId: string | null;
        role: import(".prisma/client").$Enums.UserRole;
        status: import(".prisma/client").$Enums.UserStatus;
        emailVerified: boolean;
        phoneVerified: boolean;
        twoFactorEnabled: boolean;
        lastLoginAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    delete(id: string): Promise<{
        email: string;
        password: string | null;
        id: string;
        phone: string | null;
        googleId: string | null;
        role: import(".prisma/client").$Enums.UserRole;
        status: import(".prisma/client").$Enums.UserStatus;
        emailVerified: boolean;
        phoneVerified: boolean;
        twoFactorEnabled: boolean;
        lastLoginAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    count(args?: Prisma.UserCountArgs): Promise<number>;
}
